// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Obligatorio2Web.Datos;

#nullable disable

namespace Obligatorio2Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241121205450_CrearTablasBD")]
    partial class CrearTablasBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Obligatorio2Web.Modelos.Habitacion", b =>
                {
                    b.Property<int>("NumHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumHabitacion"), 1L, 1);

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("Tarifa")
                        .HasColumnType("int");

                    b.Property<string>("TipoHabitacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Huesped", b =>
                {
                    b.Property<int>("IdHuesped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHuesped"), 1L, 1);

                    b.Property<string>("CorreoElec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumDocumento")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdHuesped");

                    b.ToTable("Huesped");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"), 1L, 1);

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.Property<bool>("RealizacionPago")
                        .HasColumnType("bit");

                    b.HasKey("IdPago");

                    b.HasIndex("IdReserva")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"), 1L, 1);

                    b.Property<DateTime>("FechaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("HabitacionElegidaNumHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdHuesped")
                        .HasColumnType("int");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<int>("NumHabitacion")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("HabitacionElegidaNumHabitacion");

                    b.HasIndex("IdHuesped");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Contrasenia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HuespedIdHuesped")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("HuespedIdHuesped");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Pago", b =>
                {
                    b.HasOne("Obligatorio2Web.Modelos.Reserva", "Reserva")
                        .WithOne("PagoReserva")
                        .HasForeignKey("Obligatorio2Web.Modelos.Pago", "IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Reserva", b =>
                {
                    b.HasOne("Obligatorio2Web.Modelos.Habitacion", "HabitacionElegida")
                        .WithMany()
                        .HasForeignKey("HabitacionElegidaNumHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio2Web.Modelos.Huesped", "Huesped")
                        .WithMany()
                        .HasForeignKey("IdHuesped")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obligatorio2Web.Modelos.Usuario", null)
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("HabitacionElegida");

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Usuario", b =>
                {
                    b.HasOne("Obligatorio2Web.Modelos.Huesped", "Huesped")
                        .WithMany()
                        .HasForeignKey("HuespedIdHuesped")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Huesped");
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Reserva", b =>
                {
                    b.Navigation("PagoReserva")
                        .IsRequired();
                });

            modelBuilder.Entity("Obligatorio2Web.Modelos.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
